# Generated by Django 6.1.1 on 2026-10-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maintenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('target_quantity', models.PositiveIntegerField()),
                ('produced_quantity', models.PositiveIntegerField(default=0)),
                ('rejected_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_runs', to='core.machine')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['machine', 'start_time'], name='core_produc_machine_20b14b_idx'), models.Index(fields=['product_code', 'batch_number'], name='core_produc_product_9f2ce1_idx')],
            },
        ),
    ]
