# Generated by Django 6.1.1 on 2026-10-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productionrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_time', models.DateTimeField()),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('REVIEW', 'Review')], max_length=10)),
                ('defect_count', models.PositiveIntegerField(default=0)),
                ('inspector_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='core.productionrun')),
            ],
            options={
                'ordering': ['-inspection_time'],
            },
        ),
    ]
