# Generated by Django 6.1.1 on 2026-10-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_defect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('MACHINE', 'Machine'), ('QUALITY', 'Quality'), ('PRODUCTION', 'Production'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.factory')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.machine')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='core_alert_status_9f08b8_idx'), models.Index(fields=['machine', 'detected_at'], name='core_alert_machine_d0c8e5_idx')],
            },
        ),
    ]
